# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cf7fb88ccf82f3b14d839cd5244a2e0c"
name = "orders remix app"
handle = "orders-remix-app"
application_url = "https://leg-ana-former-alphabetical.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = ["orders/create"]
  uri    = "/webhooks/orders_create"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders"

[auth]
redirect_urls = ["https://leg-ana-former-alphabetical.trycloudflare.com/auth/callback", "https://leg-ana-former-alphabetical.trycloudflare.com/auth/shopify/callback", "https://leg-ana-former-alphabetical.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
